### PR TITLE
Towards a fully relocatable CMake package

### PR DESCRIPTION
**Pull request by roversch**
Goals are

- `find_package(Casadi)` followed by `target_link_libraries(targetx casadi)` should suffice to build and link against CasADi from CMake, without having to call `target_include_directories`,
- A downstream user should be able to drop the CasADi binaries anywhere, and just have to set `${Casadi_DIR}` or add the Casadi path to `${CMAKE_PREFIX_PATH}`.

### CODE REVIEW

**Comment by jaeandersson** [comment]
The `master` branch points to the latest release. If you want to make a pull request, it needs to be to the `develop` branch which contains the latest development version.

**Comment by roversch** [comment]
Maybe add that to the 'contributing' page?

**Comment by jaeandersson** [comment]
Good point, I'll do this.

**Comment by jaeandersson** [comment]
Updated https://github.com/casadi/casadi/wiki/contribute

**Pull request closed without merging**
