### PR TITLE
Make SharedObject threadsafe.

### PR DESCRIPTION
**Pull request by chrisdembia**
I have successfully used parallelized `map()` but this required making `SharedObject` threadsafe by making `count` atomic (for "thread", not for "openmp").

If you'd like, I can make the `count` atomic only if `WITH_THREAD=ON`.

### CODE REVIEW

**Comment by jgillis** [comment]
Hi Chris, thanks alot.
I'm curious though for what case parallel map was not thread-safe? A large subset of functionality should already evaluate without touching count..

**Comment by chrisdembia** [comment]
I was mapping a custom Callback.

**Comment by jaeandersson** [comment]
It's hard to make the sparsity pattern stuff thread-safe since there is static memory for caches. I think a safer approach would be to mark sections of the sparsity class "critical". The sparsity patterns are never touched internally, but I can see that it could create a problem with Callback. Maybe the right approach is to avoid using casadi::DM in callback.

**Comment by chrisdembia** [comment]
Do you have suggestions for avoiding using casadi::DM in Callback? The `eval()` function requires it.

**Comment by jgillis** [comment]
Safe callbacks are now (upcoming 3.5) possible through `eval_buffer`.
Things to check before merge:
 * [ ] Support in the mingw version used for windows builds
 * [x] Consequence for timings on big SX operations: seems to be ~5% slowdown for det(SX); acceptable since this is only init time

**Comment by jgillis** [comment]
Change was incorporated in 34dfeb614c

**Comment by chrisdembia** [comment]
Thank you! This is much appreciated. :)

**Pull request closed without merging**
