### PR TITLE
Optimize get_nz by avoiding integer division

### PR DESCRIPTION
**Pull request by jackvreeken**
Integer divisions are very costly, and typically take ~20-26 clocks
cycles for 32-bit integers, and ~85-100 clock cycles for 64-bit
integers. The default size of indices was changed to 64-bit in commit
a0c6de6c6, causing a significant performance hit in one of the get_nz
methods.

This commit rewrites said get_nz method to avoid divisions, and instead
use multiplications. These have a latency of ~3 cycles, and a throughput
of 1 cycle, regardless of argument size.

### CODE REVIEW

**Comment by jackvreeken** [comment]
Few changes still needed:
1. Should not check `colind[i+1]>0)`, but `colind[i+1]>colind[i])`
2. Should add check to for loop `el<colind[i+1] && <TODO>`, that checks `*it` against `last_pos`

**Comment by jackvreeken** [comment]
1. Rewrote it a little again to use additions instead of multiplications. Not that much faster, but cleaner imo as it avoids redundant operations.
2. Checking `perf report`, it seems that the "sanity check" takes quite a bit of time as well. I am not sure if `ad_forward` calls `get_nz` with a guaranteed sorted order, but if it does it will probably be faster to skip this check (e.g. with an optional boolean parameter to `get_nz`).
3. Running `make trunktesterbot` I get one failure (that may still be OK)

```
======================================================================
FAIL: test_hess6 (__main__.Integrationtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration.py", line 737, in test_hess6
    self.assertAlmostEqual(H_out[0][0],(q0*tend**6*exp(tend**3/(3*p)))/(9*p**4)+(2*q0*tend**3*exp(tend**3/(3*p)))/(3*p**3),8,"Evaluation output mismatch")
  File "/home/pietje/dev/casadi/test/python/helpers.py", line 219, in assertAlmostEqual
    unittest.TestCase.assertAlmostEqual(self,first/n,second/n,places=places,msg=msg + "  scaled by %d" %n)
AssertionError: DM(110.149) != 110.14858783785127 within 8 places : Evaluation output mismatch 1.1014858784793719e+02 <-> 1.1014858783785127e+02  scaled by 1
```

**Comment by jaeandersson** [comment]
Note that there were some recent changes to the Sparsity class: #2189
"sanity_check" is now deprecated. The correctness of the pattern is checked only once, upon construction.

**Comment by jgillis** [comment]
Merged 29b68823a4c988d73457c31791d9cf457d1ce78d

**Comment by jaeandersson** [comment]
Nevermind my last comment. I was confusing which "sanity_check" we were talking about. Anyway, that "sanity_check" part shouldn't be there either - the indices should be correctly ordered.
Btw, this can be optimized further in the next major refactoring of the AD. The nonzero assignment and access classes (casadi::GetNonzeros, casadi::SetNonzeros) do not scale to really large scale and should be supplemented with other classes that handle special common assignments: In particular, there are the currently (unused and incomplete) casadi::SubRef and casadi::SubAssign. This would have been done long ago if it was an actual bottleneck, which is mostly hasn't been until now.

**Pull request closed without merging**
