### PR TITLE
Towards a fully relocatable CMake package

### PR DESCRIPTION
**Pull request by roversch**
Goals are

- A downstream user should be able to drop the CasADi binaries anywhere, and just have to set `${Casadi_DIR}` or add the Casadi path to `${CMAKE_PREFIX_PATH}`,
- `find_package(Casadi)` followed by `target_link_libraries(targetx casadi)` should then suffice to build and link against CasADi from CMake, without having to call `target_include_directories`.

### CODE REVIEW

**Comment by jaeandersson** [comment]
Just checking - all this should be cross-platform, right? The old code did work for MS Visual C.

**Comment by roversch** [comment]
Yes, it's all cross-platform.

**Comment by roversch** [comment]
Okay so make me a developer then 😛

**Comment by jgillis** [comment]
There is no provision for running pull requests currently in our travis..

**Comment by roversch** [comment]
But the installation always happens with relative paths starting from `${CMAKE_INSTALL_PREFIX}` right? So I would just edit that variable. The code I pushed allows for different relative paths (i.e. `${WITH_SELFCONTAINED}` `ON` or `OFF`).

Can you maybe give a concrete example of what you mean with 'editable' install directory?

**Comment by jgillis** [comment]
With editable i meant present in cmakecache, which has a gui to edit variables. We worked with absolute paths before. For example casadi would get installed within the system python libs.

**Comment by roversch** [comment]
But can't you do this by editing the `CMAKE_INSTALL_PREFIX` (which is in the cache) instead?

**Comment by jgillis** [comment]
Let's go for the compromise that cmake.in works correctly only when the default (relative) paths are being used.

**Comment by roversch** [comment]
Let's reanimate this PR. @jgillis I'm open for comments :)

**Comment by roversch** [comment]
I added the necessary changes. Key is to always use relative paths in all of the `export()` and `install()` statements. 

Please review.

**Comment by chrisdembia** [comment]
I would love to have this change.

**Comment by jgillis** [comment]
Merged in at 3616133bf1d

**Pull request closed without merging**
