### PR TITLE
bugfix: include objective sign after parsing

### PR DESCRIPTION
**Pull request by andrescodas**
Currently the sign is multiplied to zero as the objective expression is being parsed after

### CODE REVIEW

**Comment by andrescodas** [comment]
my bad... I included two independent functionalities on the same pull-request.

**Comment by jaeandersson** [comment]
@andrescodas Great that you're working on the AMPL/Pyomo interoperability! This functionality has been a bit neglected and basically untouched for some years now...

**Comment by jaeandersson** [comment]
@andrescodas I was a little too fast with accepting this.. The commits are actually breaking because of our linter, which checks style. If you make a pull request, make sure that it doesn't give errors when doing `make lint` (required `WITH_LINT` to be enabled during compilation). This was the error:
````
[  0%] Linting casadi
nlp_builder.cpp:125:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:125:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:130:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:130:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:135:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:135:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:140:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:140:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:145:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:145:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:150:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:150:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:156:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:156:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:161:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:161:  Missing space before {  [whitespace/braces] [5]
nlp_builder.cpp:166:  Missing space before ( in for(  [whitespace/parens] [5]
nlp_builder.cpp:166:  Missing space before {  [whitespace/braces] [5]
nlp_builder.hpp:103:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
Category 'whitespace/braces' errors found: 9
Category 'whitespace/parens' errors found: 9
Category 'whitespace/line_length' errors found: 1
Total errors found: 19
```
The lint error was fixed in 621243ddadd71b417422a76574b35748e88f84b0.

**Comment by andrescodas** [comment]
Interesting,  I didn't know that you were using such a tool.

By the way, I wanted to include some tests I did to the unit-testing facility but was unsure on how to do it.  It consists of running the same set of .nl files both using the bonmin executable and your interface together with NlpBuilder.  That will probably need other dependencies to read the results from the executable.

**Comment by jaeandersson** [comment]
There is an open issue, #717, for generalizing the executable. Ideally the executable should have the same usage as the executable that comes with IPOPT/Bonmin, so that it can be used as a drop-in replacement. The executable can be solver agnostic and allow you to specify the solver and options via the command line. You'd also need to print a `.sol` file with the solution. This is not a very hard thing to implement, maybe just a day's work, but we haven't really needed it for our applications, which explains why the issue has been left untouched for 4 years now..

**Pull request merged**
