### PR TITLE
Support MSVC and Ipopt Config.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR introduces 2 changes to support VC++ 2015:

1. Use `/bigobj`, which is required to compile `matrix.cpp`. TODO: I don't know the correct place to add this flag.
2. Break up a string literal into chunks under 2^16 bytes (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1091?view=vs-2017)

This PR also introduces one change to facilitate finding an Ipopt via a CMake Config file, because `pkg-config` is not on Windows (easily) and because the CMake build from [this repository](https://github.com/chrisdembia/coin/tree/ipopt_external_mumps) generates a CMake Config.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Please advise me on what to do about the TODO above.

With the above changes, I am able to compile my project that depends on CasADi and Ipopt on Windows using VC++ 2015.

**Comment by jgillis** [comment]
Thanks, Chris!

We did refactor in develop branch to not need bigobj. Could you base your pull request on develop?

**Comment by chrisdembia** [comment]
Thanks @jgillis for the quick turnaround. This is ready for review again. Let me know if you want to chat about MSVC + Ipopt support and how I can help.

**Comment by chrisdembia** [comment]
Bump.

**Comment by jgillis** [comment]
Merged in at 450eba66d5d393b455ec770c2e864222521e3eaf

**Pull request closed without merging**
