### PR TITLE
Implement a tridiagonal linear system solver

### PR DESCRIPTION
**Pull request by jbaayen**

### CODE REVIEW

**Comment by jaeandersson** [comment]
@jbaayen Good idea! The PR needs to go to develop, not master. Is there any consistency check that the linear system is actually tridiagonal?

**Comment by jbaayen** [comment]
@jaeandersson there is no consistency check at this point. I'm not sure what the best place would be to add this check (init?). Where would you suggest, and is there a better way to check than looping over the sparsity?

**Comment by jaeandersson** [comment]
Yes, during init would be the right time. You can add a helper function in the Sparsity class. Cf. Sparsity::is_diag or Sparsity::is_triu

**Comment by jgillis** [comment]
Merged in at 14a4318152

**Pull request closed without merging**
