### PR TITLE
Add the support to osqp 0.6.2

### LINKED ISSUE #2670: Unable to use casadi + osqp with an already installed version of osqp
In the laboratory in which I work (https://dic.iit.it/), we started to use `casadi` for developing MPC controllers. Our code is mainly developed using C++, so for this reason we decided to use the C++ API offered by casadi.

Right now I'm trying to build casadi for source. As far as I understood it requires a custom version of `osqp`  https://github.com/jgillis/osqp/tree/cee489483c505151b0565a35003a428535e96c9f that it's based on `osqp v0.5.0` that it is installed along with `casadi`.

In our infrastructure, we already used `osqp` along with [`osqp-eigen`](https://github.com/robotology/osqp-eigen) that is based on `osqp v0.6.0.` 
Unfortunately, as can be read from the [`osqp changelog`](https://github.com/oxfordcontrol/osqp/blob/master/CHANGELOG.md#version-060-30-august-2019) the version `0.5.0` is not compatible with `0.6.0`. This means that if we want to use casadi in our framework we have to start using [your fork](https://github.com/jgillis/osqp/tree/cee489483c505151b0565a35003a428535e96c9f) of `osqp`. 

Is there a way to use `osqp 0.6.0`? More in general, is there a way to use a system based installation of `osqp` rather than a custom implementation? If I'm not mistaken `ipopt interface` already supports this feature. (Please check [here](https://github.com/casadi/casadi/wiki/InstallationLinux#installing-ipopt-recommended-if-you-plan-to-solve-optimal-control-problems).)

cc @traversaro @s-dafarra

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR fixes #2670. In details:
1.  the `osqp_interface.cpp` has been modified in order to be compliant with `osqp 0.6.0`
2. the `osqp` submodules is now updated to `osqp 0.6.0`
3. `USE_SYSTEM_WISE_OSQP` option has been added. The default value of the option is `OFF`. When `USE_SYSTEM_WISE_OSQP` is equal to `ON`, a system installation of `osqp` is searched, if `USE_SYSTEM_WISE_OSQP` is `OFF` the repository stored in ` external_packages/osqp/osqp` is built and installed.

cc @traversaro @S-dafarra

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Hi @jgillis, if there is anything we can do to help the process of merging this PR, feel free to let us know, thanks!

**Comment by jaeandersson** [comment]
The PR should probably be directed to `develop`, not `master`. The latter points to the latest release. As for the content, I'll let @jgillis respond.

**Comment by GiulioRomualdi** [comment]
Hi @jaeandersson, thank you for your answer. I didn't know about the `develop` branch.  I'll change the base branch immediately

**Comment by GiulioRomualdi** [comment]
Since osqp [0.6.2](https://github.com/oxfordcontrol/osqp/releases/tag/v0.6.2) has been released I think that we can update the submodule.

**Comment by traversaro** [comment]
Thanks @jgillis !

**Comment by GiulioRomualdi** [comment]
Thank you @jgillis 😊

**Pull request merged**
