### PR TITLE
Adaptor newer

### PR DESCRIPTION
**Pull request by jgillis**
Passes all tests now. Open for feedback.

### CODE REVIEW

**Comment by jgillis** [comment]
Would like to see this in the upcoming release (at least  d7da163 and e3b5c28).
The other changes, I'm not 100% comfortable with. Thoughts?

**Comment by jaeandersson** [comment]
@jgillis Can you provide an executive summary? I haven't seen anything I don't like in the commits, but I haven't checked line-by-line. If I understand correctly, you are using a function "adaptorHasPlugin" for inter-plugin communication. That looks like a nice and clean solution.

**Comment by jaeandersson** [comment]
From me, merge at will.

**Comment by jgillis** [comment]
d7da163 - e3b5c28 was merged as 762f954b00ceef46c3b61fe4758b7b6ad49e92c9 - b879f17b1e36be723d6ffbc8af23155b78edad6d
The remainder is still open for debate

**Pull request closed without merging**
