### PR TITLE
added CMAKE_INSTALL_PREFIX to the python install for local builds

### PR DESCRIPTION
**Pull request by mccullerlp**
I wanted to do prefix installs for testing python. This might help some packaging as well.

### CODE REVIEW

**Comment by jgillis** [comment]
Hi!

Note that you can have local python install by specifying `-DPYTHON_PREFIX=yourlocalpythonpath` on the cmake command..

**Comment by jaeandersson** [comment]
I don't understand this PR... with this commit, the Python installation prefix would be local to the C++ installation prefix? I don't see how this would be better than just setting `PYTHON_PREFIX`.

**Comment by mccullerlp** [comment]
I must say that I didn't know of PYTHON_PREFIX when I made it. These
changes makes whatever python prefix relative to the main install prefix.

I was coming at it as if I want to install the libraries to a local
directory using the install prefix, that everything should install relative
to that directory. It seems strange the python should have its own,
separate prefix. This makes it so that the python prefix is relative to
whatever install prefix is specified.

In the end its just a style choice given that I didn't recognize the
additional option of PYTHON_PREFIX, but the previous behavior was not
intuitive to me.

Perhaps this isn't worth pulling if it would break others build scripts.

**Comment by jgillis** [comment]
We would happily accept changes to e.g. the wiki  to make this clearer, but the pull request is indeed very disruptive.

**Pull request closed without merging**
